(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 940,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Bitmap1.png?1469783991761", id:"Bitmap1"},
		{src:"images/Bitmap10.png?1469783991761", id:"Bitmap10"},
		{src:"images/Bitmap11.png?1469783991761", id:"Bitmap11"},
		{src:"images/Bitmap16.png?1469783991761", id:"Bitmap16"},
		{src:"images/Bitmap20.png?1469783991761", id:"Bitmap20"},
		{src:"images/Bitmap21.png?1469783991761", id:"Bitmap21"},
		{src:"images/Bitmap22.png?1469783991761", id:"Bitmap22"},
		{src:"images/Bitmap23.png?1469783991761", id:"Bitmap23"},
		{src:"images/Bitmap9.png?1469783991761", id:"Bitmap9"},
		{src:"images/logo.png?1469783991761", id:"logo"},
		{src:"images/logodown.png?1469783991761", id:"logodown"},
		{src:"images/logoup.png?1469783991761", id:"logoup"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,474,99);


(lib.Bitmap10 = function() {
	this.initialize(img.Bitmap10);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,423,32);


(lib.Bitmap11 = function() {
	this.initialize(img.Bitmap11);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,375,46);


(lib.Bitmap16 = function() {
	this.initialize(img.Bitmap16);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,280,46);


(lib.Bitmap20 = function() {
	this.initialize(img.Bitmap20);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,283,82);


(lib.Bitmap21 = function() {
	this.initialize(img.Bitmap21);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,211,138);


(lib.Bitmap22 = function() {
	this.initialize(img.Bitmap22);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,212,134);


(lib.Bitmap23 = function() {
	this.initialize(img.Bitmap23);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,363,46);


(lib.Bitmap9 = function() {
	this.initialize(img.Bitmap9);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,378,24);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,206,175);


(lib.logodown = function() {
	this.initialize(img.logodown);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,259,25);


(lib.logoup = function() {
	this.initialize(img.logoup);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,193,71);


(lib.URL_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.instance = new lib.Bitmap10();
	this.instance.setTransform(-123,-79);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-125.8,-88.4,430.9,42);


(lib.TopLogo_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// top logo
	this.instance = new lib.logo();
	this.instance.setTransform(-359,-35);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-359,-70.8,430.3,210.8);


(lib.Saint_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.logodown();
	this.instance.setTransform(-130,9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-130,9,259,25);


(lib.Retrouvez_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.instance = new lib.Bitmap9();
	this.instance.setTransform(-95,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-99.3,-107.9,385.6,39.8);


(lib.Resultats_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.instance = new lib.Bitmap1();
	this.instance.setTransform(-237,-63);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-241,-65,482.1,111.9);


(lib.Resultat_net_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.instance = new lib.Bitmap23();
	this.instance.setTransform(-197,-69);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-197.3,-69.3,363.3,46.3);


(lib.Resultat_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.instance = new lib.Bitmap11();
	this.instance.setTransform(-152,-52);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-152,-52,375.3,46.9);


(lib.legal_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EAuJAAnQgGgEABgGIAAgCIAOACIACADQACACAEAAQAFAAACgCQABAAAAAAQABAAAAgBQABAAAAgBQAAAAAAgBIABgGIAAgHQgGAIgJAAQgKAAgGgIQgEgHAAgJQAAgLAGgHQAGgGAJAAQAJgBAGAJIAAgIIAMAAIAAArQAAAJgBAEQgCAEgDADIgGAEQgFABgHAAQgMAAgFgFgEAuSgALQgDAEAAAHQAAAGADAEQADAEAFgBQAEABAEgEQADgEAAgGQAAgHgDgEQgDgEgFABQgFgBgDAEgAZLArIAAhDIAMAAIAAAIQACgDAEgDQAFgDAEABQAJgBAGAIQAGAGAAALQAAALgGAIQgGAGgJAAQgEAAgDgCQgEgBgDgEIAAAZgAZbgLQgDAFAAAGQAAAHADAEQAEAEAEAAQAFAAADgEQACgEAAgHQAAgGgCgFQgDgDgFAAQgFAAgDADgAJiArIAAhDIAMAAIAAAIQADgDAEgDQAEgDAFABQAIgBAHAIQAFAGAAALQAAALgFAIQgHAGgIAAQgEAAgEgCQgDgBgDgEIAAAZgAJzgLQgDAFAAAGQAAAHADAEQADAEAFAAQAEAAADgEQADgEAAgHQAAgGgDgFQgDgDgEAAQgGAAgCADgAxIArIAAhDIANAAIAAAIQACgDAEgDQAEgDAFABQAJgBAFAIQAGAGABALQgBALgGAIQgFAGgJAAQgEAAgDgCQgEgBgDgEIAAAZgAw4gLQgCAFAAAGQAAAHACAEQAEAEAEAAQAFAAADgEQADgEAAgHQAAgGgDgFQgDgDgFAAQgEAAgEADgA9hArIAAhDIANAAIAAAIQACgDAEgDQAEgDAFABQAIgBAHAIQAFAGABALQgBALgFAIQgHAGgIAAQgEAAgEgCQgDgBgDgEIAAAZgA9RgLQgCAFAAAGQAAAHACAEQAEAEAFAAQAEAAADgEQADgEAAgHQAAgGgDgFQgDgDgEAAQgFAAgEADgAG+AiQAEgBABgDQABgCABgEIgGAAIAAgNIAMAAIAAAJIgBAJQAAAEgDACIgHAEgEA1fAAVQgHgEgBgHIANgCQABAEACABQACACAFABQAFAAADgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgCIgDgCQgQgDgEgDQgHgCABgHQAAgHAEgEQAGgEAKAAQALAAAFADQAEADACAGIgMADQgBgDgCgCQgCgBgFAAQgEAAgDABQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQALADADACQAFACAAAHQgBAGgFAFQgGAFgLAAQgJAAgGgEgEA0nAARQgEgHAAgKQAAgLAGgGQAHgIAJABQALAAAGAHQAHAHAAANIghAAQAAAGADADQADAEAFAAQADgBABgCQADgBABgDIANABQgDAIgFADQgGAEgHAAQgNAAgHgIgEA0zgAMQgDAEAAAFIAUAAQgBgFgDgEQgCgCgEAAQgFAAgCACgEAy/AAYIgFgDIgCgFIAAgJIAAgUIgGAAIAAgLIAGAAIAAgJIANgIIAAARIAJAAIAAALIgJAAIAAASIABAHIABABIACABIAFgBIABAKQgEACgHAAIgFgBgEAyDAAVQgEgEAAgHQAAgDACgEQACgDAEAAIAKgDIAMgDIAAgBQAAgEgBgCQgCgBgGAAQgDAAgCABIgDAFIgMgDQACgGAFgEQAFgDAJAAQAJAAAFABQAEADABADQACADABAIIgBAOIABAKIACAGIgNAAIgBgEIgBgBQgDADgEABIgHACQgIAAgFgEgEAyVAACIgHACQgCACAAADQAAADACACQACACADAAQAEAAADgDIADgDIAAgHIAAgCIgIABgEAxRAATQgGgIAAgLQAAgLAGgGQAHgIALABQAIAAAFADQAGAFACAIIgMACQgBgEgDgCQgCgCgDAAQgGAAgCADQgDAEAAAHQAAAHADAEQACADAGAAQAEAAACgCQACgCABgFIANADQgCAIgGAEQgFAFgKAAQgKAAgHgGgEAs4AAVQgFgEgCgHIANgCQABAEACABQADACAEABQAFAAADgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgCIgDgCQgRgDgEgDQgFgCAAgHQAAgHAEgEQAGgEAKAAQAKAAAGADQAEADACAGIgMADQgBgDgCgCQgDgBgEAAQgEAAgDABQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQALADADACQAFACAAAHQAAAGgGAFQgGAFgLAAQgKAAgGgEgEArpAAVQgGgEgCgHIANgCQABAEADABQACACAFABQAFAAACgCQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIgBgCIgEgCQgQgDgEgDQgGgCAAgHQAAgHAFgEQAFgEALAAQAKAAAFADQAFADACAGIgNADQgBgDgCgCQgCgBgEAAQgFAAgDABQAAABAAAAQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIANADQAKADAEACQAEACAAAHQAAAGgGAFQgFAFgLAAQgKAAgGgEgEAqyAARQgFgHAAgKQAAgLAHgGQAGgIAJABQALAAAHAHQAGAHAAANIghAAQABAGADADQADAEAEAAQADgBACgCQACgBACgDIANABQgDAIgGADQgFAEgIAAQgNAAgGgIgEAq+gAMQgDAEgBAFIAUAAQAAgFgDgEQgCgCgEAAQgFAAgCACgEAqZAAYIgFgDIgBgFIgBgJIAAgUIgGAAIAAgLIAGAAIAAgJIANgIIAAARIAJAAIAAALIgJAAIAAASIAAAHIACABIACABIAFgBIABAKQgEACgHAAIgFgBgEAokAARQgGgHAAgKQABgLAGgGQAGgIAKABQALAAAHAHQAGAHgBANIggAAQAAAGADADQADAEAFAAQACgBACgCQADgBABgDIANABQgDAIgFADQgGAEgHAAQgOAAgFgIgEAovgAMQgDAEAAAFIAUAAQAAgFgEgEQgCgCgEAAQgEAAgDACgEAmmAAXQgFgCgBgEQgCgEAAgHIAAgeIANAAIAAAYQAAAIABACQAAABAAAAQABABAAAAQAAABABAAQAAABABAAIAEABQADAAADgCQADgBABgDQABgDAAgJIAAgVIANAAIAAAwIgNAAIAAgHQgCAEgEACQgFACgEAAQgGAAgDgCgEAltAATQgHgIABgLQgBgLAHgGQAHgIAKABQAKAAAFADQAFAFADAIIgOACQAAgEgCgCQgDgCgEAAQgFAAgCADQgDAEAAAHQAAAHADAEQACADAFAAQAEAAADgCQACgCABgFIANADQgCAIgGAEQgGAFgJAAQgLAAgGgGgEAk1AARQgEgHAAgKQgBgLAHgGQAGgIAKABQALAAAGAHQAHAHAAANIghAAQAAAGADADQADAEAEAAQAEgBACgCQACgBABgDIANABQgCAIgGADQgFAEgJAAQgMAAgHgIgEAlBgAMQgDAEAAAFIATAAQAAgFgCgEQgDgCgEAAQgFAAgCACgEAiKAAWQgGgDgDgGQgDgGAAgHQAAgGADgGQADgGAGgDQAGgDAHAAQALAAAIAHQAGAHAAAKQAAALgGAHQgIAHgKAAQgHAAgHgDgEAiPgAKQgEAEAAAGQAAAGAEAEQADAEAFAAQAGAAADgEQADgEAAgGQAAgGgDgEQgDgEgGAAQgFAAgDAEgAf6AVQgGgEgCgHIAOgCQAAAEADABQADACAFABQAEAAADgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAABgBIgBgCIgFgCQgPgDgFgDQgFgCAAgHQAAgHAEgEQAFgEAMAAQAJAAAGADQAEADACAGIgMADQgBgDgCgCQgDgBgDAAQgFAAgDABQAAABgBAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQALADADACQAEACAAAHQABAGgGAFQgFAFgLAAQgKAAgHgEgAeNAWQgHgDgCgGQgDgGAAgHQAAgGADgGQADgGAGgDQAFgDAHAAQAMAAAHAHQAHAHAAAKQAAALgHAHQgIAHgKAAQgHAAgGgDgAeRgKQgDAEgBAGQABAGADAEQADAEAFAAQAGAAADgEQAEgEAAgGQAAgGgEgEQgDgEgGAAQgFAAgDAEgAc3AVQgGgEgCgHIANgCQABAEACABQADACAFABQAFAAACgCQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIgBgCIgEgCQgQgDgEgDQgGgCAAgHQAAgHAFgEQAFgEALAAQAKAAAFADQAEADADAGIgNADQgBgDgBgCQgDgBgEAAQgFAAgDABQAAABAAAAQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIANADQAKADAEACQAEACAAAHQAAAGgGAFQgFAFgLAAQgKAAgGgEgAa0AWQgGgDgDgGQgDgGAAgHQAAgGADgGQACgGAHgDQAFgDAHAAQAMAAAHAHQAHAHAAAKQAAALgHAHQgIAHgKAAQgHAAgGgDgAa4gKQgDAEgBAGQABAGADAEQADAEAFAAQAGAAADgEQAEgEAAgGQAAgGgEgEQgDgEgGAAQgFAAgDAEgAYZAYIgFgDIgCgFIAAgJIAAgUIgGAAIAAgLIAGAAIAAgJIANgIIAAARIAJAAIAAALIgJAAIAAASIAAAHIACABIACABIAFgBIABAKQgEACgHAAIgFgBgAXdARQgEgHAAgKQgBgLAHgGQAGgIAKABQALAAAGAHQAHAHAAANIghAAQAAAGADADQADAEAEAAQADgBADgCQACgBABgDIANABQgCAIgGADQgFAEgJAAQgMAAgHgIgAXpgMQgDAEAAAFIATAAQAAgFgCgEQgDgCgEAAQgFAAgCACgAWQAVQgGgEgCgHIANgCQABAEACABQADACAFABQAFAAACgCQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIgBgCIgEgCQgQgDgEgDQgGgCAAgHQAAgHAFgEQAFgEALAAQAKAAAFADQAEADADAGIgNADQgBgDgBgCQgDgBgEAAQgFAAgDABQAAABAAAAQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIANADQAKADAEACQAEACAAAHQAAAGgGAFQgFAFgLAAQgKAAgGgEgAU7AYIgFgDIgCgFIAAgJIAAgUIgGAAIAAgLIAGAAIAAgJIANgIIAAARIAJAAIAAALIgJAAIAAASIABAHIABABIABABIAGgBIABAKQgFACgFAAIgGgBgAUCATQgGgIgBgLQABgLAGgGQAHgIALABQAIAAAFADQAGAFACAIIgMACQgBgEgDgCQgCgCgDAAQgFAAgDADQgDAEAAAHQAAAHADAEQADADAFAAQAEAAACgCQACgCABgFIANADQgCAIgGAEQgFAFgKAAQgKAAgHgGgATLAVQgFgEAAgHQAAgDACgEQACgDAEAAIAKgDIAMgDIAAgBQAAgEgCgCQgBgBgGAAQgDAAgCABIgDAFIgMgDQACgGAFgEQAFgDAKAAQAIAAAEABQAFADACADQACADAAAIIgBAOIABAKIACAGIgNAAIgBgEIAAgBQgEADgDABIgIACQgJAAgDgEgATdACIgHACQgDACAAADQAAADACACQACACADAAQADAAAEgDIADgDIAAgHIAAgCIgHABgAR8ATQgGgIAAgLQAAgLAGgHQAGgGAIAAQAJgBAGAIIAAgZIANAAIAABCIgMAAIAAgHQgDAEgEACQgEACgFAAQgIAAgGgGgASHgLQgEAEAAAHQAAAGADAEQADAFAFAAQAFAAADgEQADgEAAgHQAAgHgDgEQgDgEgFABQgFgBgCAEgAQsAVQgFgEgDgHIAOgCQAAAEADABQADACAFABQAEAAADgCQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIgBgCIgFgCQgQgDgEgDQgFgCgBgHQABgHAFgEQAEgEAMAAQAJAAAFADQAFADACAGIgMADQgBgDgCgCQgCgBgEAAQgFAAgDABQAAABgBAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQAKADAFACQADACAAAHQABAGgGAFQgFAFgLAAQgLAAgGgEgAO/AWQgGgDgDgGQgDgGgBgHQABgGADgGQACgGAHgDQAGgDAGAAQAMAAAHAHQAHAHAAAKQAAALgHAHQgHAHgLAAQgHAAgGgDgAPDgKQgDAEAAAGQAAAGADAEQAEAEAEAAQAGAAADgEQADgEABgGQgBgGgDgEQgDgEgGAAQgEAAgEAEgAOCAYIgEgDIgCgFIAAgJIAAgUIgGAAIAAgLIAGAAIAAgJIANgIIAAARIAJAAIAAALIgJAAIAAASIABAHIAAABIACABIAGgBIABAKQgFACgFAAIgHgBgANIAVQgFgEAAgHQAAgDACgEQACgDAEAAIAKgDIAMgDIAAgBQAAgEgCgCQgBgBgGAAQgDAAgCABIgDAFIgMgDQACgGAFgEQAFgDAKAAQAIAAAEABQAFADACADQACADAAAIIgBAOIABAKIACAGIgNAAIgBgEIAAgBQgEADgDABIgIACQgJAAgDgEgANaACIgHACQgDACAAADQAAADACACQACACADAAQADAAAEgDIADgDIAAgHIAAgCIgHABgAL6ATQgGgIAAgLQAAgLAGgGQAHgIALABQAJAAAFADQAFAFADAIIgNACQgBgEgCgCQgCgCgEAAQgFAAgDADQgCAEAAAHQAAAHACAEQADADAFAAQAEAAADgCQACgCAAgFIANADQgBAIgGAEQgGAFgJAAQgLAAgHgGgALDARQgFgHAAgKQAAgLAGgGQAHgIAKABQALAAAGAHQAHAHgBANIggAAQAAAGACADQADAEAFAAQADgBACgCQACgBACgDIAMABQgCAIgGADQgFAEgIAAQgNAAgGgIgALOgMQgCAEAAAFIATAAQAAgFgDgEQgDgCgDAAQgFAAgDACgAIvARQgFgHAAgKQAAgLAHgGQAGgIAJABQALAAAHAHQAGAHAAANIghAAQAAAGAEADQADAEAEAAQADgBACgCQACgBABgDIAOABQgDAIgGADQgFAEgIAAQgNAAgGgIgAI7gMQgEAEAAAFIAUAAQAAgFgDgEQgDgCgEAAQgEAAgCACgAH3ATQgGgIAAgLQAAgLAGgHQAFgGAKAAQAIgBAGAIIAAgZIANAAIAABCIgMAAIAAgHQgDAEgEACQgEACgEAAQgJAAgGgGgAIBgLQgDAEAAAHQAAAGACAEQADAFAGAAQAEAAAEgEQADgEAAgHQAAgHgDgEQgDgEgFABQgEgBgEAEgAGNAVQgGgEgCgHIANgCQABAEACABQADACAFABQAFAAACgCQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIgBgCIgEgCQgQgDgEgDQgGgCAAgHQAAgHAFgEQAFgEALAAQAKAAAFADQAFADABAGIgMADQgBgDgBgCQgDgBgEAAQgFAAgDABQAAABAAAAQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIANADQAKADAEACQAEACAAAHQAAAGgGAFQgFAFgLAAQgKAAgGgEgAEfAWQgGgDgDgGQgDgGAAgHQAAgGADgGQADgGAGgDQAGgDAHAAQALAAAIAHQAGAHAAAKQAAALgGAHQgIAHgKAAQgHAAgHgDgAEkgKQgEAEAAAGQAAAGAEAEQADAEAFAAQAGAAADgEQADgEAAgGQAAgGgDgEQgDgEgGAAQgFAAgDAEgADKAVQgHgEgBgHIANgCQABAEACABQACACAFABQAGAAACgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgCIgDgCQgQgDgEgDQgHgCAAgHQAAgHAGgEQAFgEAKAAQALAAAEADQAFADACAGIgMADQgBgDgCgCQgDgBgEAAQgFAAgCABQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQAKADAEACQAFACAAAHQgBAGgFAFQgGAFgLAAQgJAAgGgEgACVAVQgHgEgBgHIANgCQABAEACABQACACAGABQAFAAACgCQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIgCgCIgEgCQgPgDgEgDQgHgCAAgHQAAgHAGgEQAFgEAKAAQALAAAEADQAFADACAGIgMADQgBgDgCgCQgDgBgEAAQgFAAgCABQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQAKADAFACQADACAAAHQAAAGgFAFQgGAFgKAAQgLAAgFgEgABeARQgGgHAAgKQABgLAGgGQAGgIAKABQALAAAHAHQAGAHgBANIggAAQAAAGADADQADAEAFAAQACgBACgCQADgBABgDIANABQgDAIgFADQgGAEgHAAQgOAAgFgIgABpgMQgDAEAAAFIAUAAQAAgFgEgEQgCgCgEAAQgEAAgDACgAArATQgHgIAAgLQAAgLAHgGQAGgIALABQAJAAAGADQAFAFACAIIgNACQAAgEgCgCQgDgCgEAAQgEAAgDADQgDAEAAAHQAAAHADAEQADADAEAAQAEAAADgCQACgCABgFIANADQgCAIgFAEQgHAFgJAAQgKAAgHgGgAglARQgFgHAAgKQAAgLAGgGQAHgIAKABQALAAAGAHQAFAHgBANIgeAAQAAAGACADQADAEAFAAQADgBACgCQACgBABgDIALABQgBAIgEADQgGAEgIAAQgNAAgGgIgAgagMQgCAEAAAFIATAAQAAgFgDgEQgDgCgEAAQgEAAgDACgAhdATQgGgIAAgLQAAgLAGgHQAGgGAIAAQAJgBAGAIIAAgZIANAAIAABCIgMAAIAAgHQgDAEgEACQgFACgEAAQgIAAgGgGgAhSgLQgEAEAAAHQAAAGADAEQADAFAFAAQAFAAADgEQADgEAAgHQAAgHgDgEQgDgEgFABQgEgBgDAEgAisAVQgHgEgCgHIAOgCQAAAEADABQADACAFABQAFAAACgCQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIgBgCIgFgCQgQgDgDgDQgHgCAAgHQAAgHAGgEQAEgEAMAAQAJAAAFADQAFADACAGIgMADQgBgDgCgCQgCgBgEAAQgGAAgCABQAAABgBAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQAKADAFACQADACAAAHQAAAGgFAFQgGAFgKAAQgLAAgFgEgAjjARQgGgHAAgKQABgLAGgGQAHgIAJABQALAAAHAHQAGAHgBANIggAAQAAAGADADQADAEAFAAQACgBACgCQADgBABgDIANABQgDAIgFADQgGAEgHAAQgOAAgFgIgAjYgMQgDAEAAAFIAUAAQAAgFgDgEQgDgCgEAAQgEAAgDACgAkYAXQgDgCgCgEQgCgEAAgHIAAgeIANAAIAAAYQAAAIABACQAAABAAAAQABABAAAAQAAABABAAQAAABAAAAIAFABQADAAADgCQADgBABgDQABgDAAgJIAAgVIANAAIAAAwIgMAAIAAgHQgDAEgFACQgEACgFAAQgEAAgFgCgAltAVQgEgEgBgHQAAgDACgEQACgDAEAAIAKgDIANgDIAAgBQAAgEgCgCQgCgBgFAAQgDAAgCABIgEAFIgMgDQADgGAFgEQAEgDAKAAQAJAAAEABQAFADABADQACADAAAIIAAAOIABAKIABAGIgMAAIgBgEIgBgBQgEADgDABIgIACQgIAAgEgEgAlbACIgHACQgDACAAADQABADACACQACACACAAQAEAAADgDIADgDIABgHIAAgCIgIABgAn1AVQgFgEgCgHIANgCQABAEACABQADACAEABQAFAAADgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgCIgDgCQgRgDgEgDQgFgCAAgHQAAgHAEgEQAGgEAKAAQAKAAAGADQAEADACAGIgMADQgBgDgCgCQgDgBgEAAQgEAAgDABQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQALADADACQAFACAAAHQAAAGgGAFQgGAFgLAAQgKAAgGgEgAp9AWQgGgDgDgGQgDgGAAgHQAAgGADgGQADgGAGgDQAGgDAHAAQALAAAIAHQAGAHABAKQgBALgGAHQgIAHgKAAQgIAAgGgDgAp4gKQgEAEAAAGQAAAGAEAEQADAEAFAAQAGAAADgEQADgEAAgGQAAgGgDgEQgDgEgGAAQgFAAgDAEgAsoAXQgEgCgBgEQgCgEgBgHIAAgeIAOAAIAAAYQAAAIAAACQABABAAAAQAAABAAAAQABABAAAAQABABAAAAIAFABQADAAACgCQAEgBABgDQAAgDAAgJIAAgVIANAAIAAAwIgMAAIAAgHQgDAEgEACQgEACgFAAQgFAAgEgCgAtgAWQgGgDgDgGQgDgGAAgHQAAgGADgGQADgGAGgDQAGgDAHAAQALAAAIAHQAGAHAAAKQAAALgGAHQgIAHgKAAQgHAAgHgDgAtbgKQgEAEAAAGQAAAGAEAEQADAEAFAAQAFAAAEgEQADgEAAgGQAAgGgDgEQgEgEgFAAQgFAAgDAEgAu1AVQgHgEgBgHIANgCQABAEACABQACACAFABQAFAAADgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgCIgDgCQgQgDgEgDQgHgCABgHQAAgHAEgEQAFgEALAAQALAAAFADQAEADACAGIgMADQgBgDgCgCQgCgBgFAAQgEAAgDABQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQALADADACQAFACAAAHQgBAGgFAFQgGAFgLAAQgJAAgGgEgAvrAXQgEgCgCgEQgCgEAAgHIAAgeIANAAIAAAYQAAAIABACQAAABAAAAQABABAAAAQAAABABAAQAAABABAAIAEABQAEAAACgCQADgBABgDQABgDAAgJIAAgVIANAAIAAAwIgNAAIAAgHQgCAEgEACQgFACgEAAQgGAAgDgCgAyTAVQgHgEgCgHIAOgCQAAAEADABQADACAFABQAFAAACgCQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIgBgCIgFgCQgQgDgDgDQgHgCAAgHQAAgHAGgEQAEgEAMAAQAJAAAFADQAFADACAGIgMADQgBgDgCgCQgCgBgEAAQgGAAgCABQAAABgBAAQAAAAAAABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQAKADAFACQADACAAAHQAAAGgFAFQgGAFgKAAQgLAAgFgEgAzsAWQgHgDgDgGQgCgGAAgHQAAgGACgGQAEgGAFgDQAGgDAHAAQAMAAAHAHQAHAHAAAKQAAALgHAHQgIAHgKAAQgHAAgGgDgAzogKQgDAEgBAGQABAGADAEQADAEAFAAQAGAAADgEQAEgEAAgGQAAgGgEgEQgDgEgGAAQgFAAgDAEgA18AVQgGgEgCgHIAOgCQAAAEACABQADACAFABQAFAAADgCQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIgBgCIgEgCQgQgDgEgDQgGgCAAgHQAAgHAFgEQAFgEALAAQAKAAAFADQAEADACAGIgLADQgBgDgDgCQgCgBgEAAQgFAAgCABQgBABAAAAQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABABIALADQALADAEACQAEACAAAHQAAAGgFAFQgGAFgLAAQgKAAgGgEgA2zARQgFgHAAgKQAAgLAGgGQAHgIAKABQALAAAGAHQAHAHgBANIggAAQAAAGACADQADAEAFAAQADgBACgCQACgBABgDIANABQgCAIgFADQgGAEgIAAQgNAAgGgIgA2ogMQgCAEAAAFIATAAQAAgFgDgEQgDgCgEAAQgEAAgDACgA5RAXQgEgCgBgEQgCgEAAgHIAAgeIAMAAIAAAYQAAAIABACQABABAAAAQAAABAAAAQABABAAAAQABABAAAAIAFABQADAAADgCQADgBAAgDQABgDAAgJIAAgVIAOAAIAAAwIgNAAIAAgHQgCAEgFACQgEACgFAAQgFAAgEgCgA6KAVQgGgEgCgHIAOgCQAAAEACABQADACAFABQAFAAADgCQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIgBgCIgEgCQgQgDgEgDQgGgCAAgHQAAgHAFgEQAFgEALAAQAKAAAFADQAEADACAGIgLADQgBgDgDgCQgCgBgEAAQgFAAgCABQgBABAAAAQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAABABIALADQALADAEACQAEACAAAHQAAAGgFAFQgGAFgLAAQgKAAgGgEgA7lAXQgEgCgCgEQgCgEAAgHIAAgeIAOAAIAAAYQAAAIABACQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAIAEABQAEAAACgCQADgBACgDQABgDAAgJIAAgVIAMAAIAAAwIgMAAIAAgHQgCAEgFACQgEACgFAAQgFAAgEgCgA8cAWQgHgDgDgGQgDgGAAgHQAAgGADgGQADgGAGgDQAGgDAHAAQAMAAAGAHQAIAHgBAKQABALgIAHQgHAHgLAAQgGAAgGgDgA8ZgKQgDAEAAAGQAAAGADAEQAEAEAFAAQAFAAAEgEQADgEAAgGQAAgGgDgEQgEgEgFAAQgFAAgEAEgA+sAVQgHgEgBgHIANgCQABAEACABQACACAGABQAFAAACgCQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAgBIgCgCIgEgCQgQgDgDgDQgHgCAAgHQAAgHAGgEQAFgEAKAAQALAAAEADQAFADACAGIgMADQgBgDgCgCQgDgBgEAAQgFAAgCABQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQAKADAFACQADACAAAHQAAAGgFAFQgGAFgKAAQgLAAgFgEgA/jARQgGgHAAgKQABgLAGgGQAGgIAKABQALAAAHAHQAGAHgBANIggAAQAAAGADADQADAEAFAAQACgBACgCQADgBABgDIANABQgDAIgFADQgGAEgHAAQgOAAgFgIgA/YgMQgDAEAAAFIAUAAQAAgFgEgEQgCgCgEAAQgEAAgDACgA/9AYIgFgDIgBgFIgBgJIAAgUIgGAAIAAgLIAGAAIAAgJIAOgIIAAARIAJAAIAAALIgJAAIAAASIAAAHIABABIACABIAGgBIABAKQgFACgGAAIgGgBgEgiGAAYIgFgDIgBgFIgBgJIAAgUIgGAAIAAgLIAGAAIAAgJIANgIIAAARIAJAAIAAALIgJAAIAAASIAAAHIABABIADABIAFgBIABAKQgEACgHAAIgFgBgEgi/AATQgHgIABgLQgBgLAHgGQAGgIALABQAJAAAGADQAFAFADAIIgOACQAAgEgCgCQgDgCgEAAQgEAAgDADQgDAEAAAHQAAAHADAEQADADAEAAQAFAAACgCQACgCABgFIANADQgCAIgFAEQgHAFgJAAQgLAAgGgGgEgj3AAVQgEgEAAgHQAAgDACgEQACgDADAAIALgDIAMgDIAAgBQAAgEgBgCQgCgBgGAAQgDAAgCABIgDAFIgMgDQACgGAFgEQAFgDAJAAQAJAAAFABQAEADABADQACADAAAIIAAAOIABAKIACAGIgNAAIgBgEIgBgBQgDADgEABIgIACQgIAAgEgEgEgjlAACIgHACQgCACAAADQAAADACACQACACADAAQAEAAADgDIADgDIAAgHIAAgCIgIABgEglEAAVQgGgEgCgHIANgCQABAEACABQADACAFABQAFAAACgCQABAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBIgBgCIgEgCQgQgDgEgDQgGgCAAgHQAAgHAFgEQAFgEALAAQAKAAAFADQAEADADAGIgNADQgBgDgBgCQgDgBgEAAQgFAAgDABQAAABAAAAQAAAAgBABQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIANADQAKADAEACQAEACAAAHQAAAGgGAFQgFAFgLAAQgKAAgGgEgEgl7AARQgFgHAAgKQAAgLAHgGQAGgIAJABQALAAAHAHQAGAHAAANIghAAQAAAGAEADQADAEAEAAQADgBACgCQACgBABgDIAOABQgDAIgGADQgFAEgIAAQgNAAgGgIgEglvgAMQgEAEAAAFIAUAAQAAgFgDgEQgCgCgFAAQgEAAgCACgEgmzAATQgGgIAAgLQAAgLAGgHQAFgGAKAAQAIgBAGAIIAAgZIANAAIAABCIgMAAIAAgHQgDAEgEACQgEACgEAAQgJAAgGgGgEgmpgALQgDAEAAAHQAAAGACAEQADAFAGAAQAEAAAEgEQADgEAAgHQAAgHgDgEQgDgEgFABQgEgBgEAEgEgnpAAYIgEgDIgCgFIgBgJIAAgUIgFAAIAAgLIAFAAIAAgJIAOgIIAAARIAJAAIAAALIgJAAIAAASIAAAHIABABIACABIAGgBIAAAKQgEACgGAAIgGgBgEgpeAAVQgFgEABgHQAAgDACgEQACgDADAAIALgDIAMgDIAAgBQAAgEgCgCQgCgBgFAAQgDAAgDABIgDAFIgLgDQABgGAGgEQAEgDAKAAQAJAAAEABQAEADACADQACADAAAIIgBAOIACAKIACAGIgOAAIgBgEIAAgBQgEADgDABIgIACQgIAAgEgEgEgpMAACIgHACQgCACgBADQAAADACACQACACAEAAQADAAAEgDIACgDIABgHIAAgCIgIABgEgq3AAXQgEgCgBgEQgCgEgBgHIAAgeIAOAAIAAAYQAAAIAAACQABABAAAAQAAABAAAAQABABAAAAQABABAAAAIAFABQADAAACgCQAEgBABgDQAAgDAAgJIAAgVIANAAIAAAwIgMAAIAAgHQgDAEgEACQgEACgFAAQgFAAgEgCgEgrvAAWQgGgDgDgGQgDgGAAgHQAAgGADgGQADgGAGgDQAGgDAHAAQALAAAIAHQAGAHAAAKQAAALgGAHQgIAHgKAAQgHAAgHgDgEgrqgAKQgEAEAAAGQAAAGAEAEQADAEAFAAQAFAAAEgEQADgEAAgGQAAgGgDgEQgEgEgFAAQgFAAgDAEgEgspAATQgHgIAAgLQAAgLAHgGQAGgIALABQAJAAAFADQAFAFADAIIgNACQAAgEgDgCQgDgCgDAAQgFAAgCADQgEAEAAAHQAAAHAEAEQACADAFAAQAEAAACgCQADgCABgFIAMADQgCAIgFAEQgGAFgKAAQgKAAgGgGgEgtgAAYIgFgDIgBgFIAAgJIAAgUIgHAAIAAgLIAHAAIAAgJIAMgIIAAARIAJAAIAAALIgJAAIAAASIABAHIABABIACABIAFgBIABAKQgEACgGAAIgGgBgEgubAARQgFgHAAgKQAAgLAGgGQAHgIAKABQALAAAGAHQAHAHgBANIggAAQAAAGACADQADAEAFAAQADgBACgCQACgBABgDIANABQgCAIgFADQgGAEgIAAQgNAAgGgIgEguQgAMQgCAEAAAFIATAAQAAgFgDgEQgDgCgEAAQgEAAgDACgEgwTAAYIgFgDIgBgFIgBgJIAAgUIgGAAIAAgLIAGAAIAAgJIANgIIAAARIAJAAIAAALIgJAAIAAASIAAAHIABABIADABIAFgBIABAKQgEACgHAAIgFgBgEgxPAAVQgEgEAAgHQAAgDACgEQACgDADAAIALgDIANgDIAAgBQAAgEgCgCQgCgBgFAAQgEAAgCABIgDAFIgMgDQACgGAFgEQAFgDAJAAQAKAAADABQAFADABADQACADAAAIIAAAOIABAKIACAGIgNAAIgBgEIgBgBQgDADgEABIgIACQgHAAgFgEgEgw9AACIgHACQgCACAAADQAAADACACQACACADAAQAEAAADgDIADgDIABgHIAAgCIgJABgEgxoAAYIgEgDIgCgFIgBgJIAAgUIgFAAIAAgLIAFAAIAAgJIAOgIIAAARIAJAAIAAALIgJAAIAAASIAAAHIABABIACABIAGgBIAAAKQgEACgGAAIgGgBgEgy8AAXQgFgCgBgEQgCgEAAgHIAAgeIANAAIAAAYQAAAIABACQAAABAAAAQABABAAAAQAAABABAAQAAABABAAIAEABQADAAADgCQADgBABgDQABgDAAgJIAAgVIANAAIAAAwIgMAAIAAgHQgDAEgEACQgEACgFAAQgGAAgDgCgEgz2AAVQgFgEgCgHIANgCQABAEACABQADACAEABQAFAAADgCQAAAAABgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIgBgCIgDgCQgRgDgEgDQgFgCAAgHQAAgHAEgEQAGgEAKAAQAKAAAGADQAEADACAGIgMADQgBgDgCgCQgDgBgEAAQgEAAgDABQAAABgBAAQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAABABQAAAAAAAAQAAABAAAAQABAAAAABIAMADQALADADACQAFACAAAHQAAAGgGAFQgGAFgLAAQgKAAgGgEgEg0tAARQgEgHAAgKQAAgLAGgGQAGgIAKABQALAAAGAHQAHAHAAANIghAAQAAAGADADQADAEAEAAQAEgBABgCQADgBABgDIANABQgCAIgGADQgFAEgJAAQgNAAgGgIgEg0hgAMQgDAEAAAFIATAAQAAgFgDgEQgCgCgEAAQgEAAgDACgEA2QAAYIAAgNIAOAAIAAANgEAz/AAYIgUgwIANAAIANAhIABgFIACgEIAJgYIANAAIgUAwgEAzXAAYIAAgwIANAAIAAAwgEAwzAAYIAAgwIANAAIAAAwgEAwVAAYIAAglIgIAAIAAgLIAIAAIAAgDIABgJQACgEADgBQADgCAGAAIALABIgCAJIgGAAIgEABIgBAGIAAACIAJAAIAAALIgJAAIAAAlgEAv5AAYIAAgwIANAAIAAAwgEAvfAAYIAAgYIgBgJQAAgBgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBAAgBAAQgDAAgDABQgCADgBADIgBAIIAAAXIgOAAIAAgwIANAAIAAAIQAHgIAJAAQAEgBAEACQADACADACIACAFIAAAJIAAAdgEAtqAAYIAAgwIANAAIAAAwgEAp3AAYIAAgYIAAgJQgBgBAAgBQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgEAAgCABQgCADgBADIgBAIIAAAXIgOAAIAAgwIANAAIAAAIQAGgIAKAAQAEgBADACQAEACACACIACAFIABAJIAAAdgEAn9AAYIAAgwIAMAAIAAAIIAFgHQADgCADABQAFgBAEADIgFALQgDgCgCAAQgBAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAQgCACgBADQgBAEAAALIAAAPgEAnYAAYIAAgwIAMAAIAAAIIAFgHQADgCADABQAEgBAFADIgFALQgDgCgCAAQgBAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAQgCACgBADQgBAEAAALIAAAPgEAkPAAYIAAgwIAMAAIAAAIIAGgHQACgCADABQAEgBAEADIgEALQgCgCgEAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgBABAAAAQgCACgBADQgBAEAAALIAAAPgEAjaAAYIAAgYIAAgJQAAgBgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBAAgBAAQgDAAgCABQgDADgBADIgBAIIAAAXIgNAAIAAgwIAMAAIAAAIQAHgIAJAAQAFgBADACQADACACACIADAFIABAJIAAAdgEAhmAAYIAAgYIAAgJQAAgBgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBAAgBAAQgDAAgCABQgDADgBADIgBAIIAAAXIgNAAIAAgwIAMAAIAAAIQAHgIAJAAQAFgBADACQADACACACIADAFIABAJIAAAdgAfdAYIAAgYIAAgJQgBgBAAgBQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgEAAgCABQgCADgCADIAAAIIAAAXIgOAAIAAgwIANAAIAAAIQAGgIAKAAQAEgBADACQAEACACACIACAFIABAJIAAAdgAdpAYIAAgwIANAAIAAAwgAcZAYIAAgwIAOAAIAAAwgAbyAYIgUgwIANAAIAMAhIACgFIACgEIAJgYIANAAIgUAwgAaFAYIAAgwIAMAAIAAAIIAGgHQACgCADABQAEgBAEADIgDALQgDgCgEAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgBABAAAAQgCACgBADQgBAEAAALIAAAPgAVvAYIAAglIgHAAIAAgLIAHAAIAAgDIABgJQACgEADgBQAEgCAFAAIALABIgCAJIgGAAIgEABIgBAGIAAACIAJAAIAAALIgJAAIAAAlgAVTAYIAAgwIANAAIAAAwgAQPAYIAAgYIAAgJQgBgBAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgDAAgDABQgDADAAADIgBAIIAAAXIgOAAIAAgwIANAAIAAAIQAGgIAJAAQAFgBADACQAEACACACIACAFIABAJIAAAdgAObAYIAAgwIANAAIAAAwgAMsAYIAAgwIANAAIAAAwgAKdAYIAAgwIAMAAIAAAIIAFgHQACgCADABQAFgBAEADIgEALQgDgCgDAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABgBAAQgCACgBADQgBAEAAALIAAAPgAFvAYIAAgYIAAgJQAAgBgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAQgBAAAAgBQgBAAAAAAQgBAAAAAAQgBAAgBAAQgDAAgCABQgDADgBADIgBAIIAAAXIgNAAIAAgwIAMAAIAAAIQAHgIAJAAQAFgBADACQADACACACIADAFIABAJIAAAdgAD7AYIAAgwIAOAAIAAAwgAk5AYIAAhCIANAAIAABCgAmWAYIgTgwIANAAIAMAhIACgFIABgEIAJgYIANAAIgTAwgAoSAYIAAgYIgBgJQAAgBAAgBQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAQgDAAgDABQgDADgBADIgBAIIAAAXIgNAAIAAgwIAMAAIAAAIQAHgIAKAAQAEgBAEACQADACACACIADAFIAAAJIAAAdgApMAYIAAgwIANAAIAAAwgAqgAYIAAgaQAAgIgCgCQgCgCgDAAQgDAAgDABIgDAFIgBAJIAAAXIgNAAIAAgZIgBgKIgBgDIgFAAQgDAAgCABQgDACgBADIgBAIIAAAYIgMAAIAAgwIALAAIAAAIQAHgJAJABQAEAAAEABQADACACAFQAEgFADgCQAEgBAEAAQAGgBAEADQAEACACAFQABACAAAHIAAAegAwNAYIAAhCIANAAIAABCgAy8AYIAAgwIAMAAIAAAIIAFgHQADgCADABQAFgBAEADIgFALQgDgCgCAAQgBAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAQgCACgBADQgBAEAAALIAAAPgA0QAYIAAgYIgBgKIgCgDQgCgBgDAAIgGABQgCACgCADIgBAIIAAAYIgMAAIAAhCIAMAAIAAAZQAGgHAKAAQAEAAAEABQADACACADQACACAAADIABAKIAAAbgA3OAYIAAgwIAMAAIAAAwgA32AYIgUgwIAOAAIALAhIACgFIABgEIAKgYIANAAIgTAwgA4eAYIAAgwIANAAIAAAwgA6yAYIAAgwIAMAAIAAAIIAFgHQACgCADABQAFgBAEADIgEALQgDgCgDAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABgBAAQgCACgBADQgBAEAAALIAAAPgEggfAAYIAAgwIAOAAIAAAwgEghGAAYIgUgwIANAAIAMAhIACgFIACgEIAJgYIANAAIgUAwgEghuAAYIAAgwIANAAIAAAwgEgoLAAYIAAgYIAAgJQAAgBgBgBQAAAAAAgBQgBAAAAAAQAAgBgBAAQAAAAgBgBQgBAAAAAAQgBAAAAAAQgBAAAAAAQgEAAgCABQgDADgBADIgBAIIAAAXIgNAAIAAgwIAMAAIAAAIQAGgIAKAAQAEgBAEACQADACADACIACAFIABAJIAAAdgEgqEAAYIAAgwIALAAIAAAIIAGgHQADgCACABQAFgBAEADIgEALQgDgCgDAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAQgCACgCADQgBAEAAALIAAAPgEgu4AAYIgbgqIAAAqIgOAAIAAhCIAOAAIAcArIAAgrIAMAAIAABCgEgyKAAYIAAhCIAOAAIAABCgEg1FAAYIgLgPIgGgJIgFgCIgHgBIgDAAIAAAbIgNAAIAAhCIAdAAQALAAAFACQAEACADAFQAEAEAAAGQgBAHgEAFQgFAGgIABIAHAEIAIAKIAIAOgEg1lgANIALAAQAJAAADgBIAEgDQACgCgBgDQAAgEgCgBQgBgDgEgBIgKAAIgLAAgAnEAGIAAgLIAaAAIAAALgEg2agAQIAHgIIACgBIgHgBIgEgCIACgIIALAFIgBgMIAIAAIgBAMIAEgCIAHgDIADAJIgMACIAGAGIACAEIgHAEIgGgLIgHALgASzgSIgCgNIAAgLIANAAIAAALIgBANgEAlBgAeIAGgNIAPAAIgNANgALOgeIAHgNIAOAAIgNANgAI7geIAGgNIAOAAIgMANgA/YgeIAHgNIAOAAIgNANgEg0hgAeIAGgNIAPAAIgNANgEAzXgAeIAAgMIANAAIAAAMgEAwzgAeIAAgMIANAAIAAAMgEAv5gAeIAAgMIANAAIAAAMgEAtqgAeIAAgMIANAAIAAAMgAdpgeIAAgMIANAAIAAAMgAcZgeIAAgMIAOAAIAAAMgAVTgeIAAgMIANAAIAAAMgAObgeIAAgMIANAAIAAAMgAMsgeIAAgMIANAAIAAAMgAD7geIAAgMIAOAAIAAAMgApMgeIAAgMIANAAIAAAMgA3OgeIAAgMIAMAAIAAAMgA4egeIAAgMIANAAIAAAMgEggfgAeIAAgMIAOAAIAAAMgEghugAeIAAgMIANAAIAAAMg");
	this.shape.setTransform(-115.9,3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-466.6,-5.4,702.2,14.9);


(lib.desgn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 3
	this.instance = new lib.logoup();
	this.instance.setTransform(-96,-69);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-96,-69,193,102.8);


(lib.cta_btn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Calque 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#008F4C").s().p("AgjA1IACgUQALAIAMAAQAVAAAAgTQAAgRgTAAIgNAAQgCgFACgKIAJAAQATAAAAgQQAAgOgQAAQgLAAgMAHQAAgKABgJQAOgFAQAAQAMgBAJAHQALAHAAAOQAAASgTAHQAYAFAAAWQAAASgOAKQgMAJgSAAQgPAAgMgGg");
	this.shape.setTransform(191.5,11);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#008F4C").s().p("AgjA1IACgUQALAIAMAAQAUAAAAgTQAAgRgSAAIgNAAQgCgFACgKIAJAAQATAAAAgQQAAgOgQAAQgLAAgNAHQAAgLACgIQAOgFAQAAQAMgBAJAHQALAHAAAOQAAASgTAHQAYAFAAAWQAAASgOAKQgMAJgSAAQgPAAgMgGg");
	this.shape_1.setTransform(182.1,11);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#008F4C").s().p("AgjA1IACgUQALAIAMAAQAVAAAAgTQAAgRgTAAIgNAAQgBgFABgKIAJAAQATAAAAgQQAAgOgQAAQgLAAgMAHQAAgKABgJQAOgFAQAAQAMgBAJAHQALAHAAAOQAAASgTAHQAYAFAAAWQAAASgOAKQgMAJgSAAQgOAAgNgGg");
	this.shape_2.setTransform(168.7,11);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#008F4C").s().p("AgjA1IACgUQALAIAMAAQAVAAAAgTQAAgRgTAAIgNAAQgCgFACgKIAJAAQATAAAAgQQAAgOgQAAQgLAAgMAHQAAgKABgJQAOgFAQAAQAMgBAJAHQALAHAAAOQAAASgTAHQAYAFAAAWQAAASgOAKQgMAJgSAAQgPAAgMgGg");
	this.shape_3.setTransform(159.3,11);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#008F4C").s().p("AgjA6QgBgDACgNIAdgdQANgRAAgPQAAgUgOAAQgLAAgBAGIgBAIQgIgBgFgCIADgXQANgGAOAAQAOAAAKAIQANAJAAARQAAASgPARIgbAcIAsAAQAAAJgCAJg");
	this.shape_4.setTransform(145.9,10.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#008F4C").s().p("AgjA1IACgUQALAIAMAAQAVAAAAgTQAAgRgTAAIgNAAQgBgFABgKIAJAAQATAAAAgQQAAgOgQAAQgLAAgMAHQAAgKABgJQAOgFAQAAQAMgBAJAHQALAHAAAOQAAASgTAHQAYAFAAAWQAAASgOAKQgMAJgSAAQgPAAgMgGg");
	this.shape_5.setTransform(136.5,11);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#008F4C").s().p("AgoAAQAAg6AoAAQApAAAAA6QAAA7gpAAQgoAAAAg7gAgOAAQAAAqAOAAQAPAAAAgqQAAgpgPAAQgOAAAAApg");
	this.shape_6.setTransform(123.2,11);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#008F4C").s().p("AgoAAQAAg6AoAAQApAAAAA6QAAA7gpAAQgoAAAAg7gAgOAAQAAAqAOAAQAPAAAAgqQAAgpgPAAQgOAAAAApg");
	this.shape_7.setTransform(113.9,11);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#008F4C").s().p("AgaAzQgMgHAAgQQAAgRAWgLQgSgKAAgRQAAgOALgIQAKgIANAAQAOAAAJAFQALAIAAAOQAAAPgTAMQAYAIAAAVQAAAPgNAKQgLAHgPABQgPAAgLgIgAgPAbQAAAOAPAAQAPAAAAgPQAAgLgRgIQgNAJAAALgAgLgcQAAALANAHQAKgIAAgKQAAgMgMAAQgLAAAAAMg");
	this.shape_8.setTransform(104.5,11);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#008F4C").s().p("AgoAAQAAg6AoAAQApAAAAA6QAAA7gpAAQgoAAAAg7gAgOAAQAAAqAOAAQAPAAAAgqQAAgpgPAAQgOAAAAApg");
	this.shape_9.setTransform(91.1,11);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("ApvBMQASgNALgVQAJgTABgXQAAgugngcISKAAQAngBAYAWQAWAVAAAgQAAAhgWAVQgYAVgoABg");
	this.shape_10.setTransform(140.2,11.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgXAfIAAhMQAHgEAQgFIAAAcIAXAAIgCAPIgVAAIAAAlQAAAOAMAAQAHgBAFgDIgDAQQgIADgKAAQgaAAAAgYg");
	this.shape_11.setTransform(71.5,11.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgVApIAAg5QAAgHgHgCQABgIADgGQAKAAAFACQAGADADAHIAAAAQAIgNAOAAIAHABQgCANgEAJQgEgDgFAAQgIAAgFAHIAAA2g");
	this.shape_12.setTransform(65.3,12.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgiAAQAAgRAKgMQAKgMAPAAQARAAAJALQAIALAAASIgBAFIgtAAQAAALAIAGQAEAGAKAAQAKgBAKgEQgBAJgDAIQgJADgMAAQgoAAAAgqgAAOgHQAAgUgNAAQgMAAAAAUIAZAAIAAAAg");
	this.shape_13.setTransform(58,12.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgIA5IgfhcQgCgGgGgBIgHgBIAEgNIAfAAIATA8IAEAbIABAAIAchXIAWAAIgrBxg");
	this.shape_14.setTransform(50,11);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgSATQgIgIAAgLQAAgKAIgHQAIgHALAAQAMAAAIAIQAGAHAAAJQAAAMgJAHQgIAGgKAAQgKAAgIgGgAgJAAQAAAOAJAAQAKAAAAgOQAAgOgKAAQgJAAAAAOg");
	this.shape_15.setTransform(39.8,7.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAgA5Ig0hSIAABSIgUAAIAAhaQAAgIgIgBIgGgBQABgIACgFIAmAAIAkA4QAHAKAFANIABAAIgBhPIAUAAIAABxg");
	this.shape_16.setTransform(29.7,11);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#008F4C").s().p("AguAyQAPgYAAgaQAAgbgPgWIABgCIBWAsQAGADAAAEQAAAFgGADIhWAsg");
	this.shape_17.setTransform(12.6,11.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag0A0QgWgVABgfQgBgdAWgXQAXgVAdgBQAeABAXAVQAWAXgBAdQABAfgWAVQgXAXgeAAQgdAAgXgXg");
	this.shape_18.setTransform(11.7,11.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#008F4C").s().p("AuSBfQgsAAgcgcQgcgcAAgnQAAgnAcgbQAdgcArAAIcgAAQAwAAAdAcQAcAaAAAoQAAAogcAbQgeAcguAAg");
	this.shape_19.setTransform(103.4,11.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AuaBvQguAAghghQggggAAguQAAgsAgghQAhggAugBIc1AAQAuABAhAgQAgAhAAAsQAAAuggAgQghAhguAAg");
	this.shape_20.setTransform(103.5,11.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,206.9,22.2);


(lib.Chiffre_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib.Bitmap16();
	this.instance.setTransform(-134,-30);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-134,-30,280.2,46.8);


(lib._552_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.instance = new lib.Bitmap22();
	this.instance.setTransform(-133,-61);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-133,-61.4,212.2,134.4);


(lib._199_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.instance = new lib.Bitmap20();
	this.instance.setTransform(-127,-33);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-127.4,-33,283.4,82.5);


(lib._13_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy
	this.instance = new lib.Bitmap21();
	this.instance.setTransform(-60,-52);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60,-52.3,211.5,138.4);


(lib.fade = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,-125,300,250);


(lib.numerovert = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Calque 1
	this.instance = new lib.cta_btn();
	this.instance.setTransform(123,-51.4,1.737,1.737,0,0,0,103.3,10.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.4,-70.4,359.3,38.6);


// stage content:
(lib.Saint_Gobain_940x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#3554A0").ss(1,1,1).p("EhJWgTcMCStAAAMAAAAm5MiStAAAg");
	this.shape.setTransform(470,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(540));

	// fade
	this.instance = new lib.fade();
	this.instance.setTransform(470,125,3.133,1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(528).to({_off:false},0).to({alpha:1},11).wait(1));

	// Top logo
	this.instance_1 = new lib.TopLogo_mc();
	this.instance_1.setTransform(379.8,-66.9);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(136).to({_off:false},0).to({y:36.1},18,cjs.Ease.get(1)).wait(386));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EhJbATiMAAAgnDMCS2AAAMAAAAnDg");
	mask.setTransform(470,125);

	// CTA btn
	this.instance_2 = new lib.numerovert();
	this.instance_2.setTransform(-324.4,219.7);
	this.instance_2._off = true;

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(410).to({_off:false},0).to({x:454.7},12).wait(118));

	// url
	this.instance_3 = new lib.URL_mc();
	this.instance_3.setTransform(-336,184.1);
	this.instance_3._off = true;

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(406).to({_off:false},0).to({x:488,y:184},12,cjs.Ease.get(1)).wait(122));

	// Retrouvez
	this.instance_4 = new lib.Retrouvez_mc();
	this.instance_4.setTransform(-338.6,164.4);
	this.instance_4._off = true;

	this.instance_4.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(401).to({_off:false},0).to({x:483,y:164},12,cjs.Ease.get(1)).wait(127));

	// last blue bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#054C98").s().p("AgQTiMAAAgnDIAgAAMAAAAnDg");
	this.shape_1.setTransform(1.7,125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#054C98").s().p("AnkTiMAAAgnDIPJAAMAAAAnDg");
	this.shape_2.setTransform(48.5,125);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#054C98").s().p("Au4TiMAAAgnDIdxAAMAAAAnDg");
	this.shape_3.setTransform(95.4,125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#054C98").s().p("A2NTiMAAAgnDMAsaAAAMAAAAnDg");
	this.shape_4.setTransform(142.2,125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#054C98").s().p("A9hTiMAAAgnDMA7DAAAMAAAAnDg");
	this.shape_5.setTransform(189,125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#054C98").s().p("Egk1ATiMAAAgnDMBJrAAAMAAAAnDg");
	this.shape_6.setTransform(235.9,125);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#054C98").s().p("EgsJATiMAAAgnDMBYTAAAMAAAAnDg");
	this.shape_7.setTransform(282.7,125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#054C98").s().p("EgzeATiMAAAgnDMBm8AAAMAAAAnDg");
	this.shape_8.setTransform(329.5,125);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#054C98").s().p("Eg6yATiMAAAgnDMB1lAAAMAAAAnDg");
	this.shape_9.setTransform(376.4,125);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#054C98").s().p("EhCGATiMAAAgnDMCENAAAMAAAAnDg");
	this.shape_10.setTransform(423.2,125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#054C98").s().p("EhJbATiMAAAgnDMCS2AAAMAAAAnDg");
	this.shape_11.setTransform(470,125);

	this.shape_1.mask = this.shape_2.mask = this.shape_3.mask = this.shape_4.mask = this.shape_5.mask = this.shape_6.mask = this.shape_7.mask = this.shape_8.mask = this.shape_9.mask = this.shape_10.mask = this.shape_11.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1}]},389).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).wait(141));

	// legal mention
	this.instance_5 = new lib.legal_mc();
	this.instance_5.setTransform(470.7,238.2);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.instance_5.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(325).to({_off:false},0).to({alpha:1},11).wait(53).to({alpha:0},10).to({_off:true},1).wait(140));

	// 1,3 mds
	this.instance_6 = new lib._552_mc();
	this.instance_6.setTransform(-196,138.1);
	this.instance_6._off = true;

	this.instance_6.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(317).to({_off:false},0).to({x:611.9},12,cjs.Ease.get(1)).wait(60).to({y:-121.9,alpha:0},10).to({_off:true},1).wait(140));

	// Résultat net
	this.instance_7 = new lib.Resultat_net_mc();
	this.instance_7.setTransform(-193.1,102.9);
	this.instance_7._off = true;

	this.instance_7.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(311).to({_off:false},0).to({x:598.9},12,cjs.Ease.get(1)).wait(66).to({y:-137.1,alpha:0},10).to({_off:true},1).wait(140));

	// 4th red bg
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.lf(["#DD204A","#F45827"],[0,1],148.3,125,148.3,-124.9).s().p("AgQTiMAAAgnDIAgAAMAAAAnDg");
	this.shape_12.setTransform(1.7,125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.lf(["#DD204A","#F45827"],[0,1],133.5,125,133.5,-124.9).s().p("AnkTiMAAAgnDIPJAAMAAAAnDg");
	this.shape_13.setTransform(48.5,125);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["#DD204A","#F45827"],[0,1],118.7,125,118.7,-124.9).s().p("Au4TiMAAAgnDIdxAAMAAAAnDg");
	this.shape_14.setTransform(95.4,125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["#DD204A","#F45827"],[0,1],103.8,125,103.8,-124.9).s().p("A2NTiMAAAgnDMAsaAAAMAAAAnDg");
	this.shape_15.setTransform(142.2,125);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#DD204A","#F45827"],[0,1],89,125,89,-124.9).s().p("A9hTiMAAAgnDMA7DAAAMAAAAnDg");
	this.shape_16.setTransform(189,125);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#DD204A","#F45827"],[0,1],74.2,125,74.2,-124.9).s().p("Egk1ATiMAAAgnDMBJrAAAMAAAAnDg");
	this.shape_17.setTransform(235.9,125);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#DD204A","#F45827"],[0,1],59.3,125,59.3,-124.9).s().p("EgsJATiMAAAgnDMBYTAAAMAAAAnDg");
	this.shape_18.setTransform(282.7,125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.lf(["#DD204A","#F45827"],[0,1],44.5,125,44.5,-124.9).s().p("EgzeATiMAAAgnDMBm8AAAMAAAAnDg");
	this.shape_19.setTransform(329.5,125);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.lf(["#DD204A","#F45827"],[0,1],29.7,125,29.7,-124.9).s().p("Eg6yATiMAAAgnDMB1lAAAMAAAAnDg");
	this.shape_20.setTransform(376.4,125);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#DD204A","#F45827"],[0,1],14.8,125,14.8,-124.9).s().p("EhCGATiMAAAgnDMCENAAAMAAAAnDg");
	this.shape_21.setTransform(423.2,125);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.lf(["#DD204A","#F45827"],[0,1],0,125,0,-124.9).s().p("EhJbATiMAAAgnDMCS2AAAMAAAAnDg");
	this.shape_22.setTransform(470,125);

	this.shape_12.mask = this.shape_13.mask = this.shape_14.mask = this.shape_15.mask = this.shape_16.mask = this.shape_17.mask = this.shape_18.mask = this.shape_19.mask = this.shape_20.mask = this.shape_21.mask = this.shape_22.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_12}]},299).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).wait(231));

	// 1,3 mds
	this.instance_8 = new lib._13_mc();
	this.instance_8.setTransform(177.4,132.2);
	this.instance_8._off = true;

	this.instance_8.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(236).to({_off:false},0).to({regX:0.1,x:526.1,y:132},10,cjs.Ease.get(1)).wait(53).to({regX:0,x:526,y:-117.9,alpha:0},10).to({_off:true},1).wait(230));

	// Résultat
	this.instance_9 = new lib.Resultat_mc();
	this.instance_9.setTransform(197.7,85);
	this.instance_9._off = true;

	this.instance_9.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(231).to({_off:false},0).to({x:549.2,y:84},10,cjs.Ease.get(1)).wait(58).to({x:539.2,y:-192,alpha:0},10).to({_off:true},1).wait(230));

	// 3rd blue bg
	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.lf(["#0098D7","#7BC5C7"],[0,1],148.3,125,148.3,-124.9).s().p("AgQTiMAAAgnDIAgAAMAAAAnDg");
	this.shape_23.setTransform(1.7,125);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.lf(["#0298D7","#79C6C8"],[0,1],133.5,125,133.5,-124.9).s().p("AnkTiMAAAgnDIPJAAMAAAAnDg");
	this.shape_24.setTransform(48.5,125);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.lf(["#0398D6","#77C6C8"],[0,1],118.7,125,118.7,-124.9).s().p("Au4TiMAAAgnDIdxAAMAAAAnDg");
	this.shape_25.setTransform(95.4,125);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.lf(["#0598D6","#75C7C9"],[0,1],103.8,125,103.8,-124.9).s().p("A2NTiMAAAgnDMAsaAAAMAAAAnDg");
	this.shape_26.setTransform(142.2,125);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.lf(["#0698D6","#73C8C9"],[0,1],89,125,89,-124.9).s().p("A9hTiMAAAgnDMA7DAAAMAAAAnDg");
	this.shape_27.setTransform(189,125);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.lf(["#0899D6","#71C9CA"],[0,1],74.2,125,74.2,-124.9).s().p("Egk1ATiMAAAgnDMBJrAAAMAAAAnDg");
	this.shape_28.setTransform(235.9,125);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.lf(["#0999D5","#6EC9CA"],[0,1],59.3,125,59.3,-124.9).s().p("EgsJATiMAAAgnDMBYTAAAMAAAAnDg");
	this.shape_29.setTransform(282.7,125);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.lf(["#0A99D5","#6CCACA"],[0,1],44.5,125,44.5,-124.9).s().p("EgzeATiMAAAgnDMBm8AAAMAAAAnDg");
	this.shape_30.setTransform(329.5,125);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.lf(["#0C99D5","#6ACBCB"],[0,1],29.7,125,29.7,-124.9).s().p("Eg6yATiMAAAgnDMB1lAAAMAAAAnDg");
	this.shape_31.setTransform(376.4,125);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.lf(["#0D99D4","#68CBCB"],[0,1],14.8,125,14.8,-124.9).s().p("EhCGATiMAAAgnDMCENAAAMAAAAnDg");
	this.shape_32.setTransform(423.2,125);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.lf(["#0F99D4","#66CCCC"],[0,1],0,125,0,-124.9).s().p("EhJbATiMAAAgnDMCS2AAAMAAAAnDg");
	this.shape_33.setTransform(470,125);

	this.shape_23.mask = this.shape_24.mask = this.shape_25.mask = this.shape_26.mask = this.shape_27.mask = this.shape_28.mask = this.shape_29.mask = this.shape_30.mask = this.shape_31.mask = this.shape_32.mask = this.shape_33.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_23}]},219).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).wait(311));

	// 19,9 mds
	this.instance_10 = new lib._199_mc();
	this.instance_10.setTransform(-149.6,135.3);
	this.instance_10._off = true;

	this.instance_10.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(160).to({_off:false},0).to({x:571,y:134},10,cjs.Ease.get(1)).wait(49).to({regX:0.1,regY:-0.1,x:572.4,y:-104.7,alpha:0},10).to({_off:true},1).wait(310));

	// Chiffre
	this.instance_11 = new lib.Chiffre_mc();
	this.instance_11.setTransform(-138.8,89.3);
	this.instance_11._off = true;

	this.instance_11.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(155).to({_off:false},0).to({x:582,y:88},10,cjs.Ease.get(1)).wait(54).to({x:583.2,y:-150.6,alpha:0},10).to({_off:true},1).wait(310));

	// 2nd blue bg
	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.lf(["#00509C","#009CCE"],[0,1],148.3,125,148.3,-124.9).s().p("AgQTiMAAAgnDIAgAAMAAAAnDg");
	this.shape_34.setTransform(1.7,125);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.lf(["#00509C","#009CCE"],[0,1],134.8,125,134.8,-124.9).s().p("Am5TiMAAAgnDINzAAMAAAAnDg");
	this.shape_35.setTransform(44.3,125);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.lf(["#00509C","#009CCE"],[0,1],121.4,125,121.4,-124.9).s().p("AtjTiMAAAgnDIbHAAMAAAAnDg");
	this.shape_36.setTransform(86.9,125);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.lf(["#00509C","#009CCE"],[0,1],107.8,125,107.8,-124.9).s().p("A0NTiMAAAgnDMAobAAAMAAAAnDg");
	this.shape_37.setTransform(129.4,125);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.lf(["#00509C","#009CCE"],[0,1],94.4,125,94.4,-124.9).s().p("A63TiMAAAgnDMA1uAAAMAAAAnDg");
	this.shape_38.setTransform(172,125);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.lf(["#00509C","#009CCE"],[0,1],80.9,125,80.9,-124.9).s().p("EghgATiMAAAgnDMBDBAAAMAAAAnDg");
	this.shape_39.setTransform(214.6,125);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.lf(["#00509C","#009CCE"],[0,1],67.4,125,67.4,-124.9).s().p("EgoKATiMAAAgnDMBQVAAAMAAAAnDg");
	this.shape_40.setTransform(257.1,125);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.lf(["#00509C","#009CCE"],[0,1],54,125,54,-124.9).s().p("Egu0ATiMAAAgnDMBdoAAAMAAAAnDg");
	this.shape_41.setTransform(299.7,125);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.lf(["#00509C","#009CCE"],[0,1],40.5,125,40.5,-124.9).s().p("Eg1dATiMAAAgnDMBq7AAAMAAAAnDg");
	this.shape_42.setTransform(342.3,125);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.lf(["#00509C","#009CCE"],[0,1],27,125,27,-124.9).s().p("Eg8HATiMAAAgnDMB4PAAAMAAAAnDg");
	this.shape_43.setTransform(384.9,125);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.lf(["#00509C","#009CCE"],[0,1],13.5,125,13.5,-124.9).s().p("EhCxATiMAAAgnDMCFjAAAMAAAAnDg");
	this.shape_44.setTransform(427.4,125);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.lf(["#00509C","#009CCE"],[0,1],0,125,0,-124.9).s().p("EhJbATiMAAAgnDMCS2AAAMAAAAnDg");
	this.shape_45.setTransform(470,125);

	this.shape_34.mask = this.shape_35.mask = this.shape_36.mask = this.shape_37.mask = this.shape_38.mask = this.shape_39.mask = this.shape_40.mask = this.shape_41.mask = this.shape_42.mask = this.shape_43.mask = this.shape_44.mask = this.shape_45.mask = mask;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_34}]},124).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).wait(405));

	// Résultats
	this.instance_12 = new lib.Resultats_mc();
	this.instance_12.setTransform(470.4,132.4,1,1,0,0,0,0.1,0.1);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.instance_12.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(66).to({_off:false},0).to({x:470.1,y:132.1,alpha:1},9).wait(49).to({regY:-0.1,x:470.4,y:-63.7,alpha:0},11).to({_off:true},1).wait(404));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_0 = new cjs.Graphics().p("Ah0HFIAAuJIDqAAIAAOJg");
	var mask_1_graphics_1 = new cjs.Graphics().p("AiiHFIAAuJIFFAAIAAOJg");
	var mask_1_graphics_2 = new cjs.Graphics().p("AjQHFIAAuJIGhAAIAAOJg");
	var mask_1_graphics_3 = new cjs.Graphics().p("Aj+HFIAAuJIH9AAIAAOJg");
	var mask_1_graphics_4 = new cjs.Graphics().p("AkrHFIAAuJIJXAAIAAOJg");
	var mask_1_graphics_5 = new cjs.Graphics().p("AlZHFIAAuJIKzAAIAAOJg");
	var mask_1_graphics_6 = new cjs.Graphics().p("AmHHFIAAuJIMPAAIAAOJg");
	var mask_1_graphics_7 = new cjs.Graphics().p("Am1HFIAAuJINrAAIAAOJg");
	var mask_1_graphics_8 = new cjs.Graphics().p("AniHFIAAuJIPFAAIAAOJg");
	var mask_1_graphics_9 = new cjs.Graphics().p("AoQHFIAAuJIQhAAIAAOJg");
	var mask_1_graphics_10 = new cjs.Graphics().p("Ao+HFIAAuJIR9AAIAAOJg");
	var mask_1_graphics_11 = new cjs.Graphics().p("ApsHFIAAuJITZAAIAAOJg");
	var mask_1_graphics_12 = new cjs.Graphics().p("AqZHFIAAuJIU0AAIAAOJg");
	var mask_1_graphics_13 = new cjs.Graphics().p("ArHHFIAAuJIWPAAIAAOJg");
	var mask_1_graphics_14 = new cjs.Graphics().p("Ar1HFIAAuJIXrAAIAAOJg");
	var mask_1_graphics_15 = new cjs.Graphics().p("AsjHFIAAuJIZHAAIAAOJg");
	var mask_1_graphics_16 = new cjs.Graphics().p("AtQHFIAAuJIahAAIAAOJg");
	var mask_1_graphics_17 = new cjs.Graphics().p("At+HFIAAuJIb9AAIAAOJg");
	var mask_1_graphics_18 = new cjs.Graphics().p("AusHFIAAuJIdZAAIAAOJg");
	var mask_1_graphics_19 = new cjs.Graphics().p("AvaHFIAAuJIe1AAIAAOJg");
	var mask_1_graphics_20 = new cjs.Graphics().p("AwHHFIAAuJMAgPAAAIAAOJg");
	var mask_1_graphics_21 = new cjs.Graphics().p("Aw1HFIAAuJMAhrAAAIAAOJg");
	var mask_1_graphics_22 = new cjs.Graphics().p("AxjHFIAAuJMAjHAAAIAAOJg");
	var mask_1_graphics_23 = new cjs.Graphics().p("AyRHFIAAuJMAkjAAAIAAOJg");
	var mask_1_graphics_24 = new cjs.Graphics().p("Ay+HFIAAuJMAl+AAAIAAOJg");

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:mask_1_graphics_0,x:358.4,y:102.8}).wait(1).to({graphics:mask_1_graphics_1,x:362.9,y:102.8}).wait(1).to({graphics:mask_1_graphics_2,x:367.5,y:102.8}).wait(1).to({graphics:mask_1_graphics_3,x:372.1,y:102.8}).wait(1).to({graphics:mask_1_graphics_4,x:376.7,y:102.8}).wait(1).to({graphics:mask_1_graphics_5,x:381.2,y:102.8}).wait(1).to({graphics:mask_1_graphics_6,x:385.8,y:102.8}).wait(1).to({graphics:mask_1_graphics_7,x:390.4,y:102.8}).wait(1).to({graphics:mask_1_graphics_8,x:395,y:102.8}).wait(1).to({graphics:mask_1_graphics_9,x:399.5,y:102.8}).wait(1).to({graphics:mask_1_graphics_10,x:404.1,y:102.8}).wait(1).to({graphics:mask_1_graphics_11,x:408.7,y:102.8}).wait(1).to({graphics:mask_1_graphics_12,x:413.3,y:102.8}).wait(1).to({graphics:mask_1_graphics_13,x:417.8,y:102.8}).wait(1).to({graphics:mask_1_graphics_14,x:422.4,y:102.8}).wait(1).to({graphics:mask_1_graphics_15,x:427,y:102.8}).wait(1).to({graphics:mask_1_graphics_16,x:431.6,y:102.8}).wait(1).to({graphics:mask_1_graphics_17,x:436.1,y:102.8}).wait(1).to({graphics:mask_1_graphics_18,x:440.7,y:102.8}).wait(1).to({graphics:mask_1_graphics_19,x:445.3,y:102.8}).wait(1).to({graphics:mask_1_graphics_20,x:449.9,y:102.8}).wait(1).to({graphics:mask_1_graphics_21,x:454.4,y:102.8}).wait(1).to({graphics:mask_1_graphics_22,x:459,y:102.8}).wait(1).to({graphics:mask_1_graphics_23,x:463.6,y:102.8}).wait(1).to({graphics:mask_1_graphics_24,x:468.2,y:102.8}).wait(31).to({graphics:null,x:0,y:0}).wait(485));

	// logo dsgn
	this.instance_13 = new lib.desgn();
	this.instance_13.setTransform(514.3,160.1,1,1,0,0,0,44.3,17.1);

	this.instance_13.mask = mask_1;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(44).to({alpha:0},10).to({_off:true},1).wait(485));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	var mask_2_graphics_13 = new cjs.Graphics().p("A3aFmIAArLMAu2AAAIAALLg");

	this.timeline.addTween(cjs.Tween.get(mask_2).to({graphics:null,x:0,y:0}).wait(13).to({graphics:mask_2_graphics_13,x:470,y:153.7}).wait(42).to({graphics:null,x:0,y:0}).wait(485));

	// logo
	this.instance_14 = new lib.Saint_mc();
	this.instance_14.setTransform(470,185);
	this.instance_14._off = true;

	this.instance_14.mask = mask_2;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(13).to({_off:false},0).to({y:148},11).wait(20).to({alpha:0},10).to({_off:true},1).wait(485));

	// 1st blue bg
	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#0D4E96").s().p("AgJTiMAAAgnDIASAAMAAAAnDg");
	this.shape_46.setTransform(1,125);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#0D4E96").s().p("AneTiMAAAgnDIO8AAMAAAAnDg");
	this.shape_47.setTransform(47.9,125);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#0D4E96").s().p("AuzTiMAAAgnDIdnAAMAAAAnDg");
	this.shape_48.setTransform(94.8,125);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#0D4E96").s().p("A2ITiMAAAgnDMAsRAAAMAAAAnDg");
	this.shape_49.setTransform(141.7,125);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#0D4E96").s().p("A9dTiMAAAgnDMA66AAAMAAAAnDg");
	this.shape_50.setTransform(188.6,125);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#0D4E96").s().p("EgkyATiMAAAgnDMBJkAAAMAAAAnDg");
	this.shape_51.setTransform(235.5,125);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#0D4E96").s().p("EgsHATiMAAAgnDMBYPAAAMAAAAnDg");
	this.shape_52.setTransform(282.4,125);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#0D4E96").s().p("EgzcATiMAAAgnDMBm5AAAMAAAAnDg");
	this.shape_53.setTransform(329.3,125);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#0D4E96").s().p("Eg6xATiMAAAgnDMB1iAAAMAAAAnDg");
	this.shape_54.setTransform(376.2,125);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#0D4E96").s().p("EhCGATiMAAAgnDMCEMAAAMAAAAnDg");
	this.shape_55.setTransform(423.1,125);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#0D4E96").s().p("EhJbATiMAAAgnDMCS2AAAMAAAAnDg");
	this.shape_56.setTransform(470,125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_46}]},55).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).wait(475));

	// bg
	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("EhJbATiMAAAgnDMCS2AAAMAAAAnDg");
	this.shape_57.setTransform(470,125);

	this.timeline.addTween(cjs.Tween.get(this.shape_57).wait(540));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(440,124.5,1000,251);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;